ProyEntidadBancaria/Presentation/EntidadBancaria.UI.MVC/Models/SucursalViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace EntidadBancaria.UI.MVC.Models
{
    public class SucursalViewModel
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Nombre { get; set; }
        [Required]
        [MaxLength(100)]
        public string Direccion { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaDeRegistro { get; set; }
        [Required]
        public int IdBanco { get; set; }
        public string Banco { get; set; }
    }
}

ProyEntidadBancaria/Presentation/EntidadBancaria.UI.MVC/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntidadBancaria.Business.Component;
using EntidadBancaria.UI.MVC.Models;
using EntidadBancaria.Entities.Entidades;
using AutoMapper;
using EntidadBancaria.Entities.Enumeration;

namespace EntidadBancaria.UI.MVC.Controllers
{
    public class SucursalController : Controller
    {
        private SucursalComponent sucursalComponent = new SucursalComponent();
        public ActionResult Listar(int idBanco=0)
        {
            var bancoComponent=new BancoComponent();
            ViewBag.Bancos = new SelectList(bancoComponent.Listar()??Enumerable.Empty<Banco>(),"Id","Nombre");
            var sucursales = sucursalComponent.Listar(idBanco).Select(x => new SucursalViewModel()
            {
                Nombre = x.Nombre,
                Direccion = x.Direccion,
                FechaDeRegistro = x.FechaDeRegistro,
                Id = x.Id,
                IdBanco=x.IdBanco,
                Banco=x.Banco.Nombre
            });
            return View(sucursales);
        }
        public ActionResult Editar(int id = 0)
        {
            var bancoComponent = new BancoComponent();
            ViewBag.Bancos = new SelectList(bancoComponent.Listar() ?? Enumerable.Empty<Banco>(), "Id", "Nombre");
            if (id == 0)
                return View(new SucursalViewModel());
            else
            {
                var sucursal = sucursalComponent.ObtenerById(id);
                Mapper.CreateMap<Sucursal, SucursalViewModel>();
                var sucursalViewModel = Mapper.Map<Sucursal, SucursalViewModel>(sucursal);
                return View(sucursalViewModel);
            }
        }

        public ActionResult Guardar(SucursalViewModel sucursalViewModel)
        {
            Mapper.CreateMap<SucursalViewModel, Sucursal>();
            var banco = Mapper.Map<SucursalViewModel, Sucursal>(sucursalViewModel);

            var result = sucursalViewModel.Id > 0 ?
                    sucursalComponent.Actualizar(banco) :
                    sucursalComponent.Registrar(banco);

            if (!result)
            {
                ViewBag.Mensaje = "Ocurrio un error al guardar informacion de sucursal";
                return View("~/Views/Shared/_Mensajes.cshtml");
            }

            return Redirect("~/");
        }
        public ActionResult Eliminar(int id)
        {
            var result = sucursalComponent.Eliminar(id);

            if (!result)
            {
                ViewBag.Mensaje = "Ocurrio un error al eliminar sucursal";
                return View("~/Views/Shared/_Mensajes.cshtml");
            }

            return Redirect("~/");
        }

    }
}

ProyEntidadBancaria/Presentation/EntidadBancaria.UI.MVC/Views/Sucursal/Editar.cshtml
@model EntidadBancaria.UI.MVC.Models.SucursalViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Crear/Editar Sucursal</h2>
<div>
    @using (Html.BeginForm("Guardar", "Sucursal", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.Id)
        <div class="row">
            <div class="col-md-10">
                @Html.LabelFor(x => x.Nombre, "NOMBRE", new { Class = "control-label" })
                @Html.TextBoxFor(x => x.Nombre, new { Class = "form-control input-sm" })
                @Html.ValidationMessageFor(x => x.Nombre)
            </div>
        </div>
        <div class="row">
            <div class="col-md-10">
                @Html.LabelFor(x => x.Direccion, "DIRECCION", new { Class = "control-label" })
                @Html.TextBoxFor(x => x.Direccion, new { Class = "form-control input-sm" })
                @Html.ValidationMessageFor(x => x.Direccion)
            </div>
        </div>
        <div class="row">
            <div class="col-md-10">
                @Html.LabelFor(x => x.FechaDeRegistro, "FECHA DE REGISTRO", new { Class = "control-label" })
                @Html.EditorFor(X => X.FechaDeRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(x => x.FechaDeRegistro)
            </div>
        </div>
        <div class="row">
            <div class="col-md-10">
                @Html.LabelFor(x => x.IdBanco,"BANCO", new { Class = "control-label" })
                @Html.DropDownListFor(x => x.IdBanco, ViewBag.Bancos as SelectList, "--Seleccionar--", new { Class = "form-control input-sm"})
                @Html.ValidationMessageFor(x => x.IdBanco)
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3">
                <input type="submit" value="GRABAR" class="btn btn-danger" />
            </div>
        </div>
    }
</div>

ProyEntidadBancaria/Presentation/EntidadBancaria.UI.MVC/Views/Sucursal/Listar.cshtml
@model IEnumerable<EntidadBancaria.UI.MVC.Models.SucursalViewModel>
@{
    ViewBag.Title = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SUCURSALES</h2>
<div>
    <p>
        @Html.ActionLink("Nueva Sucursal", "Editar")
    </p>
    <div>
        @using (Html.BeginForm("Listar", "Sucursal", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-10">
                    @Html.Label("IdBanco", "BANCO", new { Class = "control-label" })
                    @Html.DropDownList("IdBanco", ViewBag.Bancos as SelectList, "--Seleccione--", new { Class = "form-control input-sm"})						
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-3">
                    <input type="submit" value="Buscar" class="btn btn-danger" />
                </div>
            </div>
        }
    </div>
    <table class="table">
        <tr>
            <th>NOMBRE</th>
            <th>DIRECCION</th>
            <th>FECHA DE REGISTRO</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Nombre
                </td>
                <td>
                    @item.Direccion
                </td>
                <td>
                    @item.FechaDeRegistro
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                    @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</div>