ProyEntidadBancaria/Presentation/EntidadBancaria.UI.MVC/Models/OrdenDePagoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using EntidadBancaria.Entities.Enumeration;
using EntidadBancaria.Entities.Entidades;

namespace EntidadBancaria.UI.MVC.Models
{
    public class OrdenDePagoViewModel
    {
        public int Id { get; set; }
        [Required]
        public decimal Monto { get; set; }
        [Required]
        public MonedaEnum Moneda { get; set; }
        public string MonedaDesc { get; set; }
        [Required]
        public EstadoOrdenPagoEnum Estado { get; set; }
        public string EstadoDesc { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaDePago { get; set; }
        public int IdSucursal { get; set; }
        public string Sucursal { get; set; }
    }
}

ProyEntidadBancaria/Presentation/EntidadBancaria.UI.MVC/Controllers/OrdenDePagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntidadBancaria.Business.Component;
using EntidadBancaria.UI.MVC.Models;
using EntidadBancaria.Entities.Entidades;
using AutoMapper;
using EntidadBancaria.Entities.Enumeration;
using EntidadBancaria.Framework;

namespace EntidadBancaria.UI.MVC.Controllers
{
    public class OrdenDePagoController : Controller
    {
        private OrdenDePagoComponent ordenComponent = new OrdenDePagoComponent();

        public ActionResult Listar(int idSucursal=0)
        {
            var sucursalComponent = new SucursalComponent();
            ViewBag.Sucursales = new SelectList(sucursalComponent.ListarTodas() ?? Enumerable.Empty<Sucursal>(), "Id", "Nombre");
            var ordenes = ordenComponent.Listar(idSucursal).Select(x => new OrdenDePagoViewModel()
            {
                Id=x.Id,
                EstadoDesc=x.Estado.GetDisplayName(),
                FechaDePago=x.FechaDePago,
                IdSucursal=x.IdSucursal,
                MonedaDesc=x.Moneda.GetDisplayName(),
                Monto=x.Monto,
                Sucursal=x.Sucursal.Nombre
            });
            return View(ordenes);
        }
        public ActionResult Editar(int id = 0)
        {
            ViewBag.Monedas = MonedaEnum.Dolares.ToSelectList("",true);
            ViewBag.Estados = EstadoOrdenPagoEnum.Anulada.ToSelectList("",true);
            var sucursalComponent = new SucursalComponent();
            ViewBag.Sucursales = new SelectList(sucursalComponent.ListarTodas() ?? Enumerable.Empty<Sucursal>(), "Id", "Nombre");
            if (id == 0)
                return View(new OrdenDePagoViewModel());
            else
            {
                var orden = ordenComponent.ObtenerById(id);
                Mapper.CreateMap<OrdenDePago, OrdenDePagoViewModel>();
                var ordenDePagoViewModel = Mapper.Map<OrdenDePago, OrdenDePagoViewModel>(orden);
                return View(ordenDePagoViewModel);
            }
        }

        public ActionResult Guardar(OrdenDePagoViewModel ordenPagoViewModel)
        {
            Mapper.CreateMap<OrdenDePagoViewModel, OrdenDePago>();
            var ordenDePago = Mapper.Map<OrdenDePagoViewModel, OrdenDePago>(ordenPagoViewModel);

            var result = ordenPagoViewModel.Id > 0 ?
                    ordenComponent.Actualizar(ordenDePago) :
                    ordenComponent.Registrar(ordenDePago);

            if (!result)
            {
                ViewBag.Mensaje = "Ocurrio un error al guardar informacion de orden de pago";
                return View("~/Views/Shared/_Mensajes.cshtml");
            }

            return Redirect("~/");
        }
        public ActionResult Eliminar(int id)
        {
            var result = ordenComponent.Eliminar(id);

            if (!result)
            {
                ViewBag.Mensaje = "Ocurrio un error al eliminar orden de pago";
                return View("~/Views/Shared/_Mensajes.cshtml");
            }

            return Redirect("~/");
        }

    }
}

ProyEntidadBancaria/Presentation/EntidadBancaria.UI.MVC/Views/OrdenDePago/Editar.cshtml
@model EntidadBancaria.UI.MVC.Models.OrdenDePagoViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Crear/Editar Orden De Pago</h2>
<div>
    @using (Html.BeginForm("Guardar", "OrdenDePago", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.Id)
        <div class="row">
            <div class="col-md-10">
                @Html.LabelFor(x => x.Monto, "MONTO", new { Class = "control-label" })
                @Html.TextBoxFor(x => x.Monto, new { Class = "form-control input-sm" })
                @Html.ValidationMessageFor(x => x.Monto)
            </div>
        </div>
        <div class="row">
            <div class="col-md-10">
                @Html.LabelFor(x => x.Moneda, "MONEDA", new { Class = "control-label" })
                @Html.DropDownListFor(x => x.Moneda, ViewBag.Monedas as SelectList, new { Class = "form-control input-sm" })
                @Html.ValidationMessageFor(x => x.Moneda)
            </div>
        </div>
    <div class="row">
        <div class="col-md-10">
            @Html.LabelFor(x => x.Estado, "ESTADOS", new { Class = "control-label" })
            @Html.DropDownListFor(x => x.Estado, ViewBag.Estados as SelectList, new { Class = "form-control input-sm" })
            @Html.ValidationMessageFor(x => x.Estado)
        </div>
    </div>
        <div class="row">
            <div class="col-md-10">
                @Html.LabelFor(x => x.FechaDePago, "FECHA DE PAGO", new { Class = "control-label" })
                @Html.EditorFor(X => X.FechaDePago, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(x => x.FechaDePago)
            </div>
        </div>
        <div class="row">
            <div class="col-md-10">
                @Html.LabelFor(x => x.IdSucursal, "SUCURSAL", new { Class = "control-label" })
                @Html.DropDownListFor(x => x.IdSucursal, ViewBag.Sucursales as SelectList, "--Seleccionar--", new { Class = "form-control input-sm" })
                @Html.ValidationMessageFor(x => x.IdSucursal)
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3">
                <input type="submit" value="GRABAR" class="btn btn-danger" />
            </div>
        </div>
    }
</div>

ProyEntidadBancaria/Presentation/EntidadBancaria.UI.MVC/Views/OrdenDePago/Listar.cshtml
@model IEnumerable<EntidadBancaria.UI.MVC.Models.OrdenDePagoViewModel>
@{
    ViewBag.Title = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ORDENES DE PAGO</h2>
<div>
    <p>
        @Html.ActionLink("Nueva Orden de Pago", "Editar")
    </p>
    <div>
        @using (Html.BeginForm("Listar", "OrdenDePago", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-10">
                    @Html.Label("IdSucursal", "SUCURSAL", new { Class = "control-label" })
                    @Html.DropDownList("IdSucursal", ViewBag.Sucursales as SelectList, "--Seleccione--", new { Class = "form-control input-sm" })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-3">
                    <input type="submit" value="Buscar" class="btn btn-danger" />
                </div>
            </div>
        }
    </div>
    <table class="table">
        <tr>
            <th>MONTO</th>
            <th>MONEDA</th>
            <th>ESTADO</th>
            <th>FECHA DE PAGO</th>
            <th>SUCURSAL</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Monto
                </td>
                <td>
                    @item.MonedaDesc
                </td>
                <td>
                    @item.EstadoDesc
                </td>
                <td>
                    @item.FechaDePago
                </td>
                <td>
                    @item.Sucursal
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                    @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</div>