ProyEntidadBancaria/Presentation/EntidadBancaria.UI.MVC/Models/BancoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace EntidadBancaria.UI.MVC.Models
{
    public class BancoViewModel
    {
        public virtual int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public virtual string Nombre { get; set; }
        [Required]
        [MaxLength(100)]
        public virtual string Direccion { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public virtual DateTime FechaDeRegistro { get; set; }
    }
}

ProyEntidadBancaria/Presentation/EntidadBancaria.UI.MVC/Controllers/BancoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntidadBancaria.Business.Component;
using EntidadBancaria.UI.MVC.Models;
using EntidadBancaria.Entities.Entidades;
using AutoMapper;

namespace EntidadBancaria.UI.MVC.Controllers
{
    public class BancoController : Controller
    {
        private BancoComponent bancoComponent = new BancoComponent();

        public ActionResult Listar()
        {
            var bancos = bancoComponent.Listar().Select(x => new BancoViewModel()
                {
                    Nombre = x.Nombre,
                    Direccion = x.Direccion,
                    FechaDeRegistro = x.FechaDeRegistro,
                    Id = x.Id
                });
            return View(bancos);
        }
        public ActionResult Editar(int id=0)
        {
            if(id==0)
                return View(new BancoViewModel());
            else
            {
                var banco = bancoComponent.ObtenerById(id);
                Mapper.CreateMap<Banco, BancoViewModel>();
                var bancoViewModel = Mapper.Map<Banco, BancoViewModel>(banco);
                return View(bancoViewModel);
            }
        }

        public ActionResult Guardar(BancoViewModel bancoViewModel)
        {
            Mapper.CreateMap<BancoViewModel, Banco>();
            var banco = Mapper.Map<BancoViewModel, Banco>(bancoViewModel);

            var result = bancoViewModel.Id > 0 ?
                    bancoComponent.Actualizar(banco) :
                    bancoComponent.Registrar(banco);

            if (!result)
            {
                ViewBag.Mensaje = "Ocurrio un error al guardar informacion del Banco";
                return View("~/Views/Shared/_Mensajes.cshtml");
            }

            return Redirect("~/");
        }
        public ActionResult Eliminar(int id)
        {
            var result = bancoComponent.Eliminar(id);

            if (!result)
            {
                ViewBag.Mensaje = "Ocurrio un error al eliminar el banco";
                return View("~/Views/Shared/_Mensajes.cshtml");
            }

            return Redirect("~/");
        }
    }
}

ProyEntidadBancaria/Presentation/EntidadBancaria.UI.MVC/Views/Banco/Editar.cshtml
@model EntidadBancaria.UI.MVC.Models.BancoViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Crear/Editar Banco</h2>
<div>
    @using (Html.BeginForm("Guardar","Banco",FormMethod.Post))
    {
        @Html.HiddenFor(x => x.Id)
        <div class="row">
            <div class="col-md-10">
                @Html.LabelFor(x => x.Nombre, "NOMBRE", new { Class = "control-label" })
                @Html.TextBoxFor(x => x.Nombre, new { Class = "form-control input-sm" })
                @Html.ValidationMessageFor(x=>x.Nombre)
            </div>
        </div>
        <div class="row">
            <div class="col-md-10">
                @Html.LabelFor(x => x.Direccion, "DIRECCION", new { Class = "control-label" })
                @Html.TextBoxFor(x => x.Direccion, new { Class = "form-control input-sm" })
                @Html.ValidationMessageFor(x => x.Direccion)
            </div>
        </div>
        <div class="row">
            <div class="col-md-10">
                @Html.LabelFor(x => x.FechaDeRegistro, "FECHA DE REGISTRO", new { Class = "control-label" })
                @Html.EditorFor(X => X.FechaDeRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(x => x.FechaDeRegistro)
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3">
                <input type="submit" value="GRABAR" class="btn btn-danger" />
            </div>
        </div>
    }
</div>

ProyEntidadBancaria/Presentation/EntidadBancaria.UI.MVC/Views/Banco/Listar.cshtml
@model IEnumerable<EntidadBancaria.UI.MVC.Models.BancoViewModel>
@{
    ViewBag.Title = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>BANCOS</h2>
<div>
    <p>
        @Html.ActionLink("Nuevo Banco", "Editar")
    </p>
    <table class="table">
        <tr>
            <th>NOMBRE</th>
            <th>DIRECCION</th>
            <th>FECHA DE REGISTRO</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Nombre
                </td>
                <td>
                    @item.Direccion
                </td>
                <td>
                    @item.FechaDeRegistro
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                    @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</div>